### ISSUE TITLE
Support hightlight Drag Zone when upload file ?

### ISSUE THREAD

**Issue by forsigner** [keeema/pure-upload#14]

**Comment by keeema** [comment]
Highlighting is currently not supported but it is planned. I will check the possibilities and add it in one of next versions.

**Comment by keeema** [comment]
Added in version 4.2.0.

New area optionss:
dragOverStyle?: string;
dragOverGlobalStyle?: string;

**Comment by forsigner** [comment]
Nice && Thx~
