### ISSUE TITLE
 Does the "accept" actually work?

### ISSUE THREAD

**Issue by hchoriq** [keeema/pure-upload#15]
It doesn't seem to. If so, is it comma-separated? How do I limit the files I can select, in the browser file picker?

**Comment by keeema** [comment]
Yes it does - I have tried it on the latest version to be sure. It simply provides such configuration to the created input element (you can find this element in the body to check it) so you can follow [input accept attribute rules](https://www.w3schools.com/tags/att_input_accept.asp).
The `accept` parameter only defines the input element. If you use a file extension limit and assign `validateExtension: true` then the basic validation of extension performs. It simply parse a list of extensions (comma-separated) and tries to find the uploaded one.
